### ISSUE TITLE
reload matchengine config file

### ISSUE THREAD

**Issue by SimonVillage** [qyvlik/viabtc_exchange_server_docker#5]
Is there an easy way to reload the config file after adding a new currency / market?

**Comment by qyvlik** [comment]
@TAiS46  Need to modify the source code, you can ask the developer of [viabtc_exchange_server](https://github.com/viabtc/viabtc_exchange_server).

**Comment by SimonVillage** [comment]
asked here: https://github.com/viabtc/viabtc_exchange_server/issues/92

close here for now. Will update again once I need some help from this side.
