### ISSUE TITLE
请问WS服务怎么开启呢？

### ISSUE THREAD

**Issue by acd28705** [qyvlik/viabtc_exchange_server_docker#7]
如题。

**Comment by alberthitanaya** [comment]
Add this service to docker-compose.yml

`nginx:
    image: nginx
    volumes:
      - "./nginx/sites-enabled/socket.conf:/etc/nginx/conf.d/socket.conf"
      - "./btc/tmp:/sockets"
    ports:
      - "8008:8008"`

Add a file called /nginx/sites-enabled/socket.conf

`
server {
	listen 0.0.0.0:8008;`

	location / {
		proxy_pass http://unix:/sockets/accessws.sock:/;
		proxy_redirect off;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
		proxy_send_timeout 1d;
		proxy_read_timeout 1d;
		proxy_connect_timeout 1d;
		proxy_set_header X-Real-IP $remote_addr;
	}

}
`
The websocket will be accessible on port 8008 of your viabtc server service.

**Comment by shunshun1023** [comment]
> Add this service to docker-compose.yml
> 
> `nginx: image: nginx volumes: - "./nginx/sites-enabled/socket.conf:/etc/nginx/conf.d/socket.conf" - "./btc/tmp:/sockets" ports: - "8008:8008"`
> 
> Add a file called /nginx/sites-enabled/socket.conf
> 
> ` server { listen 0.0.0.0:8008;`
> 
> ```
> location / {
> 	proxy_pass http://unix:/sockets/accessws.sock:/;
> 	proxy_redirect off;
> 
> 	proxy_http_version 1.1;
> 	proxy_set_header Upgrade $http_upgrade;
> 	proxy_set_header Connection "Upgrade";
> 	proxy_send_timeout 1d;
> 	proxy_read_timeout 1d;
> 	proxy_connect_timeout 1d;
> 	proxy_set_header X-Real-IP $remote_addr;
> }
> ```
> 
> }
> `
> The websocket will be accessible on port 8008 of your viabtc server service.

I followed the way above, but there was an error during the websocket connection.

WebSocket connection to 'ws://45.76.192.160:8008/' failed: Error during WebSocket handshake: Unexpected response code: 502
