### ISSUE TITLE
請問docker-compose up得此問題?

### ISSUE THREAD

**Issue by zutronn** [qyvlik/viabtc_exchange_server_docker#8]
btc-redis-sentinel | 1:X 05 Aug 17:38:25.487 * +slave slave 172.21.0.2:6379 172.21.0.2 6379 @ mymaster 172.21.0.5 6379

btc-service       | [2018-08-05 17:48:18.533943] [73] [error]me_message.c:36(on_logger): RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:mq:9092/bootstrap]: mq:9092/bootstrap: Receive failed: Disconnected

像是 btc-redis-sentinel的IP Address不能connect.

**Comment by qyvlik** [comment]
@zutronn 
1. 检查一下 redis 是否启动
2. redis 的网络在 viabtc 程序所在的容器中是否可以ping通
3. 检查 docker 的版本
4. 检查 docker network 的连通性
5. 检查 docker 容器内的 host 和 dns

**Comment by zutronn** [comment]
@qyvlik 
Thankyou, solved.
